name: isle_x_flutter
description: Live a day as a local.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^1.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_circle.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/mitsos.png
    - assets/images/apostolis.png
    - assets/images/katerina.png
    - assets/images/marilena.png
    - assets/images/mitsos_icon.png
    - assets/images/activities/peacock.png
    - assets/images/activities/food.png
    - assets/images/activities/coffee.png
    - assets/images/activities/cd.jpg
    # //TODO: bring these files from online... its time lost to add them in yaml..

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FiraSans
      fonts:
        - asset: fonts/fira_sans_semibold.ttf #appbar title, capital, 10% letter space, size 15
        - asset: fonts/fira_sans_light.ttf #appbar subtitle, capital, size 15
          style: normal
    - family: FiraSansCondensed
      fonts:
        - asset: fonts/fira_sans_condensed_extralight.ttf #card titles, size 22
        - asset: fonts/fira_sans_condensed_extrabold.ttf #buttons, capital, size 15
        - asset: fonts/fira_sans_condensed_light.ttf # -
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
